### ISSUE TITLE
Слова цывілізаваным пераўтвараецца ў cyviłizavanym, але павінна быць cyvilizavanym (з l мяккім)

### ISSUE THREAD

**Issue by b83** [skip405/bel-lat#1]

**Comment by skip405** [comment]
Рабіў у адпаведнасці [з правіламі](https://be.wikipedia.org/wiki/%D0%91%D0%B5%D0%BB%D0%B0%D1%80%D1%83%D1%81%D0%BA%D1%96_%D0%BB%D0%B0%D1%86%D1%96%D0%BD%D1%81%D0%BA%D1%96_%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D1%96%D1%82#%D0%90%D0%B4%D0%BF%D0%B0%D0%B2%D0%B5%D0%B4%D0%BD%D0%B0%D1%81%D1%86%D1%8C_%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D1%96%D1%82%D0%B0%D1%9E_%D0%BA%D1%96%D1%80%D1%8B%D0%BB%D1%96%D1%86%D1%8B_%D1%96_%D0%BB%D0%B0%D1%86%D1%96%D0%BD%D0%BA%D1%96) на Вікі.

А там:

> Варыянт «Ll» выкарыстоўваецца перад галоснымі «е», «ё», «ю» «я» ці перад мяккім знакам, іначай варыянт «Łł».

Знайшоў у іншых крыніцах (больш лінгвістычных) што перад `і` таксама павінна быць `l`. Выпраўлю, дзякуй.

**Comment by skip405** [comment]
Дзякуй, зроблена

**Comment by b83** [comment]
Дзякуй за хуткі фікс :)
